---

- hosts: all
  become: true
  tasks:

  - name: install updates for all Rocky Linux servers
    dnf:
      update_only: yes
      update_cache: yes



- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for all web servers
    dnf:
      name:
        - httpd
        - php
      state: latest



- hosts: file_servers
  become: true
  tasks:

  - name: install samba package for all file servers
    package:
      name: samba
      state: latest
